all:
	make -C iPad1,1
	make -C iPhone2,1
	make -C iPhone3,1
	make -C iPod2,1
	make -C iPod3,1
	make -C iPod4,1
	make -C AppleTV2,1

clean:
	make clean -C iPad1,1
	make clean -C iPhone2,1
	make clean -C iPhone3,1
	make clean -C iPod2,1
	make clean -C iPod3,1
	make clean -C iPod4,1
	make clean -C AppleTV2,1
	
